web_service=https://www.kielipankki.fi/korp/api8/
corpus=KLK_SV_1915
query=[word = "och" & pos = "KN"] [] [pos = "NN"]
expected_word=och

# web_service=https://ws.spraakbanken.gu.se/ws/korp/v8/
# corpus=SUC2